"""Character spec table — canon-grounded colours + signature details.
Drives the parametric generator for cohesive overworld + battle art."""
from pixutil import hx

SK = hx('#f1c6a0'); SK2 = hx('#e8bd96'); TAN = hx('#e0b488')
PALE = hx('#ecdcc8'); GAARA = hx('#f0cdb0')
LEAF = hx('#2b53a6'); MIST = hx('#46566a'); SAND = hx('#3a4250'); SOUND = hx('#5a3a6a')
PLATE = hx('#aab4be')

# overworld + battle character specs (key = unit_id or npc id)
OVER = {
 'naruto': dict(skin=SK, hair=hx('#f4cf3a'), top=hx('#ee7b1c'), pants=hx('#ee7b1c'),
                trim=hx('#1b2a4a'), band=LEAF, eyes=hx('#3f86d0'), hair_style='spiky',
                marks=['whiskers']),
 'naruto_sage': dict(skin=SK, hair=hx('#f4cf3a'), top=hx('#ee7b1c'), pants=hx('#ee7b1c'),
                trim=hx('#b33a00'), band=LEAF, eyes=hx('#e0a81e'), hair_style='spiky',
                marks=['whiskers', 'sage']),
 'sasuke': dict(skin=SK2, hair=hx('#2b2f4a'), top=hx('#27408b'), pants=hx('#dcdce2'),
                trim=hx('#16244a'), band=hx('#3a3f4a'), eyes=hx('#2a2a33'), hair_style='duck'),
 'sasuke_cm2': dict(skin=PALE, hair=hx('#3a3550'), top=hx('#5a4a7a'), pants=hx('#2a2238'),
                trim=hx('#1a1026'), band=hx('#3a3f4a'), eyes=hx('#c83a3a'), hair_style='duck',
                marks=['curse']),
 'sakura': dict(skin=SK, hair=hx('#f0a0bd'), top=hx('#d8566c'), pants=hx('#2f6f6a'),
                trim=hx('#9c2838'), band=hx('#d8566c'), eyes=hx('#3f9f86'), hair_style='bob'),
 'sakura_apprentice': dict(skin=SK, hair=hx('#f0a0bd'), top=hx('#d8566c'), pants=hx('#7a1f33'),
                trim=hx('#ffffff'), band=hx('#d8566c'), eyes=hx('#3f9f86'), hair_style='bob',
                marks=['seal_mark']),
 'kakashi': dict(skin=SK2, hair=hx('#bcc3cb'), top=hx('#1f2d3d'), pants=hx('#1f2d3d'),
                vest=hx('#3f6f4a'), trim=hx('#2a5a3a'), mask=hx('#1f2d3d'), band=hx('#3a3f4a'),
                band_style='slant', hair_style='spiky'),
 'rock_lee': dict(skin=SK, hair=hx('#1b1b22'), top=hx('#3a8a3a'), pants=hx('#3a8a3a'),
                trim=hx('#1f6f2f'), hair_style='bowl', brows=hx('#1b1b22'),
                band=hx('#1f6f2f'), band_style='neck', legwarm=hx('#ffb330')),
 'gaara': dict(skin=GAARA, hair=hx('#b3402c'), top=hx('#26222c'), pants=hx('#201d26'),
                trim=hx('#e8e0cc'), eyes=hx('#86b6b6'), hair_style='spiky',
                extras=['gourd', 'sash'], marks=['eye_rings', 'kanji_ai']),
 'gaara_kazekage': dict(skin=GAARA, hair=hx('#b3402c'), top=hx('#dcdcd0'), pants=hx('#c8c8bc'),
                trim=hx('#2a4a6a'), eyes=hx('#86b6b6'), hair_style='spiky',
                extras=['gourd'], marks=['eye_rings', 'kanji_ai']),
 'temari': dict(skin=SK, hair=hx('#d8c060'), top=hx('#26222e'), pants=hx('#201d26'),
                trim=hx('#b03a4a'), band=hx('#46566a'), band_style='neck',
                eyes=hx('#5a7f7a'), hair_style='temari', extras=['fan']),
 'kankuro': dict(skin=SK2, hair=hx('#2a2a32'), top=hx('#222229'), pants=hx('#1f1f26'),
                hair_style='hood', hood=hx('#222229'), cat_ears=True, eyes=hx('#3a3a44'),
                trim=hx('#9c3a4a'), marks=['facepaint'], extras=['puppet']),
 'shikamaru': dict(skin=SK2, hair=hx('#26261f'), top=hx('#54603e'), pants=hx('#3a4030'),
                trim=hx('#2a3320'), band=LEAF, eyes=hx('#33333a'), hair_style='pineapple'),
 'choji': dict(skin=SK, hair=hx('#9a5a2a'), top=hx('#4a7a3a'), pants=hx('#3a5a2e'),
                trim=hx('#f0e8d8'), band=LEAF, eyes=hx('#5a4a3a'), hair_style='spiky',
                marks=['swirl'], big=True),
 'ino': dict(skin=SK, hair=hx('#f4d24a'), top=hx('#9a6ac0'), pants=hx('#5a3a8a'),
                trim=hx('#4a3a6a'), band=LEAF, eyes=hx('#3f86d0'), hair_style='ponytail'),
 'kiba': dict(skin=SK2, hair=hx('#7a4a2a'), top=hx('#8a8a7a'), pants=hx('#4a4a40'),
                trim=hx('#5a5a4a'), band=LEAF, eyes=hx('#5a3a2a'), hair_style='spiky',
                marks=['fang'], extras=['akamaru']),
 'shino': dict(skin=SK2, hair=hx('#2a2a2a'), top=hx('#3a4a4a'), pants=hx('#2a3636'),
                hair_style='hood', hood=hx('#3a4a4a'), glasses=hx('#202020')),
 'hinata': dict(skin=SK, hair=hx('#2c2c3a'), top=hx('#e8dfc6'), pants=hx('#2a3260'),
                trim=hx('#d6c9a6'), band=hx('#2b53a6'), band_style='neck',
                eyes=hx('#e6e2f2'), hair_style='bob'),
 'neji': dict(skin=SK2, hair=hx('#3a3328'), top=hx('#d8d0c0'), pants=hx('#7a6a50'),
                trim=hx('#4a4438'), band=LEAF, eyes=hx('#e6e2f2'), hair_style='long'),
 'tenten': dict(skin=SK, hair=hx('#4a3326'), top=hx('#c05a78'), pants=hx('#2a6f6a'),
                trim=hx('#7a2a44'), band=LEAF, eyes=hx('#5a3a2a'), hair_style='bun_twin'),
 'jiraiya': dict(skin=SK2, hair=hx('#e8e8e8'), top=hx('#4a6a4a'), pants=hx('#3a4a3a'),
                vest=hx('#a83232'), trim=hx('#7a2424'), band=hx('#9a2f2f'), plate=PLATE,
                haori_dots=True, eyes=hx('#3a3a44'), hair_style='sannin',
                marks=['facelines'], extras=['scroll']),
 'tsunade': dict(skin=SK, hair=hx('#e8d090'), top=hx('#bcbcb0'), pants=hx('#3a6a3a'),
                vest=hx('#3a6a3a'), trim=hx('#90c8e8'), eyes=hx('#8a6a3a'),
                hair_style='long', marks=['seal_mark']),
 'orochimaru': dict(skin=PALE, hair=hx('#1f1a26'), top=hx('#cfc8b0'), pants=hx('#b8b09a'),
                trim=hx('#7a3a9a'), eyes=hx('#c0a020'), hair_style='orochi', marks=['facepaint']),
 'zabuza': dict(skin=SK2, hair=hx('#3a4250'), top=hx('#6a7280'), pants=hx('#3a444e'),
                band=hx('#46566a'), band_style='slant', eyes=hx('#3a3a44'), hair_style='spiky',
                marks=['bandage'], extras=['sword']),
 'haku': dict(skin=PALE, hair=hx('#2a2a34'), top=hx('#9ac6d6'), pants=hx('#5a7a86'),
                trim=hx('#f4f8ff'), eyes=hx('#5a4a3a'), hair_style='long'),
 # generic wilds (ninja kind)
 'leaf_genin': dict(skin=SK, hair=hx('#5a3a24'), top=hx('#4a7a4a'), pants=hx('#2f4a2f'),
                trim=hx('#1f3320'), band=LEAF, eyes=hx('#3a3a44'), hair_style='short'),
 'sound_genin': dict(skin=SK2, hair=hx('#3a3340'), top=hx('#6a6a86'), pants=hx('#2a2a3a'),
                hair_style='hood', hood=hx('#6a6a86'), eyes=hx('#3a3a44')),
 'mist_swordsman': dict(skin=SK2, hair=hx('#46505e'), top=hx('#6a8a9a'), pants=hx('#34424c'),
                band=hx('#46566a'), band_style='slant', eyes=hx('#3a3a44'),
                hair_style='spiky', extras=['sword']),
 'custom_template': dict(skin=SK, hair=hx('#5a5a5a'), top=hx('#888888'), pants=hx('#444444'),
                trim=hx('#dddddd'), band=LEAF, eyes=hx('#3a3a44'), hair_style='short'),
 # NPCs
 'hokage': dict(skin=hx('#e8cba8'), hair=hx('#c8c4bc'), top=hx('#e6e0d2'), pants=hx('#d8d2c2'),
                trim=hx('#b23a3a'), eyes=hx('#4a4438'), hair_style='short', npc_hat='hokage'),
 'iruka': dict(skin=SK2, hair=hx('#3a2f24'), top=hx('#2f5a8a'), pants=hx('#2a3a4a'),
                vest=hx('#3f6f4a'), band=LEAF, eyes=hx('#3a2f24'), hair_style='ponytail',
                marks=['scar']),
 'ichiraku': dict(skin=hx('#e8cba8'), hair=hx('#5a4636'), top=hx('#f0ece0'), pants=hx('#caa86a'),
                trim=hx('#b23a3a'), eyes=hx('#4a3a2a'), hair_style='short', npc_hat='chef'),
 'teuchi': dict(skin=hx('#e8cba8'), hair=hx('#5a4636'), top=hx('#f0ece0'), pants=hx('#caa86a'),
                trim=hx('#b23a3a'), eyes=hx('#4a3a2a'), hair_style='short', npc_hat='chef'),
 'shopkeep': dict(skin=SK2, hair=hx('#3a2f24'), top=hx('#8a6a3a'), pants=hx('#5a4630'),
                trim=hx('#caa86a'), eyes=hx('#3a2f24'), hair_style='short'),
 'konohamaru': dict(skin=SK, hair=hx('#5a4030'), top=hx('#e8c84a'), pants=hx('#3a5a8a'),
                eyes=hx('#3a2f24'), hair_style='spiky', extras=['scarf'], npc_hat='goggles'),
 'villager_m': dict(skin=SK, hair=hx('#3a2f24'), top=hx('#5a7a8a'), pants=hx('#3a4a52'),
                eyes=hx('#3a3a44'), hair_style='short'),
 'villager_f': dict(skin=SK, hair=hx('#6a4636'), top=hx('#c87a9a'), pants=hx('#7a4a5a'),
                eyes=hx('#3a3a44'), hair_style='bob'),
}

# battle-only creature units handled by a separate generator
CREATURES = ['forest_snake', 'giant_centipede']

ORDER = ['naruto', 'sasuke', 'sakura', 'kakashi', 'rock_lee', 'neji', 'tenten',
         'shikamaru', 'choji', 'ino', 'kiba', 'shino', 'hinata',
         'gaara', 'temari', 'kankuro', 'jiraiya', 'tsunade', 'orochimaru',
         'zabuza', 'haku', 'naruto_sage', 'sasuke_cm2', 'gaara_kazekage',
         'sakura_apprentice', 'leaf_genin', 'sound_genin', 'mist_swordsman',
         'hokage', 'iruka', 'ichiraku', 'konohamaru']
