import fs from 'fs';
import path from 'path';
import { all, get } from '../db.js';
import { discoverMemoryDirs } from './discovery.js';
import { calculateStreak } from '../utils/streak.js';

export async function exportDashboardStatus() {
  const dirs = discoverMemoryDirs();

  if (dirs.length === 0) {
    console.warn('No Claude memory dirs found; skipping dashboard export.');
    return { written: [], skipped: [], errors: [] };
  }

  const results = { written: [], skipped: [], errors: [] };

  for (const dir of dirs) {
    try {
      const statusPath = path.join(dir, 'INCOME_HUNT_STATUS.md');
      const content = await generateStatusMarkdown();

      // Atomic write: .tmp first, then rename
      const tmpPath = statusPath + '.tmp';
      fs.writeFileSync(tmpPath, content, 'utf-8');
      fs.renameSync(tmpPath, statusPath);

      results.written.push(statusPath);
    } catch (e) {
      console.error(`Error exporting to ${dir}:`, e.message);
      results.errors.push({ dir, message: e.message });
    }
  }

  return results;
}

async function generateStatusMarkdown() {
  const now = new Date().toISOString();

  // Gather data
  const expData = await all(`SELECT * FROM experiments ORDER BY path ASC`);
  const revenue = await get(`SELECT SUM(revenueCumulative) as total FROM experiments`);
  const targetData = await get(`SELECT revenueCumulative FROM experiments WHERE path = 'ai-consulting'`);

  const countdown = await get(`SELECT CAST((julianday('2026-12-01') - julianday('now')) AS INTEGER) as daysLeft`);
  const daysLeft = countdown?.daysLeft || 0;
  const totalDays = 184;
  const elapsed = totalDays - daysLeft;
  const timelinePct = Math.min(100, (elapsed / totalDays) * 100);

  const totalRevenue = revenue?.total || 0;
  const target = 5000;
  const pct = Math.min(100, (totalRevenue / target) * 100);
  const behindPace = pct < timelinePct;
  const catchUpPace = daysLeft > 0 ? Math.ceil((target - totalRevenue) / daysLeft) : 0;

  // Next move
  const task = await get(`SELECT taskName FROM tasks WHERE date = date('now') AND status != 'completed' ORDER BY priority DESC LIMIT 1`);
  const nextAction = task?.taskName || 'Plan one money-moving action';

  // Streak
  const { currentStreak } = await calculateStreak();

  // Latest milestone
  const milestone = await get(`SELECT * FROM earned_milestones ORDER BY earnedAt DESC LIMIT 1`);

  // Uber (last 7 days)
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
  const sevenDaysStr = sevenDaysAgo.toISOString().slice(0, 10);
  const uberData = await get(`
    SELECT SUM(earnings) as earnings, SUM(hours) as hours, SUM(trips) as trips
    FROM uber_shifts WHERE date >= ?
  `, [sevenDaysStr]);

  const uberEarnings = uberData?.earnings || 0;
  const uberHours = uberData?.hours || 0;
  const uberTrips = uberData?.trips || 0;
  const uberPerHour = uberHours > 0 ? Math.round((uberEarnings / uberHours) * 10) / 10 : 0;

  // Expenses (last 30 days)
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const thirtyDaysStr = thirtyDaysAgo.toISOString().slice(0, 10);
  const expenseData = await get(`
    SELECT SUM(amount) as total FROM expenses
    WHERE date >= ? AND deductible = 1
  `, [thirtyDaysStr]);

  const totalDeductions = expenseData?.total || 0;

  // Recent facts
  const recentFacts = await all(`
    SELECT sourceQuote, sourceDate FROM extracted_facts
    WHERE sourceQuote IS NOT NULL
    ORDER BY createdAt DESC
    LIMIT 5
  `);

  // Build markdown
  let md = `<!-- AUTO-GENERATED BY INCOME HUNT — DO NOT EDIT MANUALLY · last update: ${now} -->\n`;
  md += `# Income Hunt — Live Status\n\n`;

  md += `## North Star\n`;
  md += `- **Target:** $5,000 CAD/month · **Deadline:** Dec 1, 2026 (${daysLeft} days left)\n`;
  md += `- **This month:** $${Math.round(totalRevenue)} earned (${Math.round(pct)}% of target) · **On pace:** ${behindPace ? 'no ❌' : 'yes ✅'}\n`;
  if (behindPace) {
    md += `  - Catch-up needed: $${catchUpPace}/day\n`;
  } else {
    md += `  - Projected month-end: $${Math.round(totalRevenue + (target - totalRevenue) * (daysLeft / totalDays))}\n`;
  }

  md += `\n## Right Now\n`;
  md += `- 🎯 **Focus today:** ${nextAction}\n`;
  md += `- 🔥 **Streak:** ${currentStreak}-day consistency\n`;
  if (milestone) {
    md += `- 🏆 **Latest milestone:** ${milestone.message}\n`;
  }

  md += `\n## Income Paths\n`;
  for (const exp of expData) {
    const status = exp.status === 'completed' ? '✅' : exp.status === 'paused' ? '⏸️' : '🚀';
    md += `- **${exp.name}** ${status}\n`;
    md += `  - Revenue: $${Math.round(exp.revenueCumulative)} cumulative · ${Math.round(exp.revenueThisMonth)} this month\n`;
    md += `  - Hours: ${Math.round(exp.hoursInvested * 10) / 10}h invested\n`;
    if (exp.nextAction) md += `  - Next: ${exp.nextAction}\n`;
  }

  md += `\n## Uber (last 7 days)\n`;
  md += `- **Earnings:** $${Math.round(uberEarnings)} · **Hours:** ${Math.round(uberHours * 10) / 10}h · **Trips:** ${uberTrips}\n`;
  md += `- **Rate:** $${uberPerHour}/hour\n`;

  md += `\n## Expenses (last 30 days)\n`;
  md += `- **Total deductions:** $${Math.round(totalDeductions)}\n`;

  if (recentFacts.length > 0) {
    md += `\n## Recently Logged\n`;
    for (const fact of recentFacts) {
      md += `- *${fact.sourceDate}:* "${fact.sourceQuote}"\n`;
    }
  }

  return md;
}
